version: '3.8'
services:
  dev-db:
    image: 430amdev/bookshelf-db:latest
    container_name: dev-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_NAME: postgres
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
    ports:
      - 5433:5432
    volumes:
      - ~/pgdata:/var/lib/postgresql/data
    networks:
      - alagaesia
networks:
  alagaesia:
