version: '3.8'
services:
  dev-db:
    image: postgres:14
    container_name: dev-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookshelfDB
    ports:
      - 5433:5432
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    networks:
      - alagaesia

  test-db:
    image: postgres:14
    container_name: test-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookshelfDB
    ports:
      - 5434:5432
    networks:
      - alagaesia

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=password
    networks:
      - alagaesia
    ports:
      - '5050:80'
    restart: always

networks:
  alagaesia:
