version: '3.8'
services:
  dev-db:
    image: postgres:14
    container_name: dev-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5433:5432
    volumes:
      - /pgdata:/var/lib/postgresql/data
    networks:
      - alagaesia

  test-db:
    image: postgres:14
    container_name: test-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5434:5432
    networks:
      - alagaesia

networks:
  alagaesia:
